# -*- coding: utf-8 -*-
"""iris_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-wLhBol9EKEjXXkyOHEX2YN-MrxtZx-
"""

import streamlit as st
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# Cargar datos
iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

# Entrenar modelo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = KNeighborsClassifier(n_neighbors=3)
modelo.fit(X_train, y_train)
accuracy = accuracy_score(y_test, modelo.predict(X_test))

# Interfaz de usuario
st.title("🌸 Clasificador de Flores - Iris con KNN")
st.write("Selecciona las características de una flor para predecir su especie.")

# Inputs del usuario
sepal_length = st.slider("Largo del sépalo (cm)", 4.0, 8.0, 5.1)
sepal_width = st.slider("Ancho del sépalo (cm)", 2.0, 4.5, 3.5)
petal_length = st.slider("Largo del pétalo (cm)", 1.0, 7.0, 1.4)
petal_width = st.slider("Ancho del pétalo (cm)", 0.1, 2.5, 0.2)

# Predicción
entrada = [[sepal_length, sepal_width, petal_length, petal_width]]
prediccion = modelo.predict(entrada)[0]
especie = target_names[prediccion]

# Mostrar resultados
st.subheader("🌼 Predicción del modelo:")
st.success(f"La flor es probablemente una **{especie}**.")

st.subheader("📊 Precisión del modelo:")
st.info(f"{accuracy * 100:.2f}% en datos de prueba.")

streamlit run iris_app.py